# Generated by Django 4.2.7 on 2023-12-07 08:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('emaila', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('employee_id', models.IntegerField(blank=True, db_index=True, default=None, null=True, unique=True)),
                ('omk2', models.CharField(db_index=True, default=None, max_length=5, null=True)),
                ('hcm', models.CharField(db_index=True, default=None, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manufact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, null=True)),
                ('manufact', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Manufact',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, null=True)),
                ('manufact', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
            ],
            options={
                'db_table': 'Model',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist', models.CharField(max_length=20, null=True)),
                ('manufact', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(null=True)),
                ('variant', models.CharField(null=True)),
                ('price', models.CharField(null=True)),
            ],
            options={
                'db_table': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufact', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(null=True)),
                ('variant', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
                ('cc', models.CharField(null=True)),
                ('locator', models.CharField(null=True)),
            ],
            options={
                'db_table': 'Variant',
            },
        ),
        migrations.CreateModel(
            name='VM_10_VSPEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdbtime', models.DateTimeField(null=True)),
                ('manufact', models.CharField(null=True)),
                ('model', models.CharField(null=True)),
                ('variant', models.CharField(null=True)),
                ('options', models.CharField(null=True)),
                ('desciption', models.CharField(null=True)),
            ],
            options={
                'db_table': 'VM_10_VSPEC',
            },
        ),
    ]
